version: '3.8'

services:
  # nginx:
  #   build: 
  #     dockerfile: ./docker/frontend.dockerfile
  #     context: .
  #   image: my-nginx:v1
  #   container_name: server_nginx
  #   ports:
  #     - '8080:80'
  #   networks:
  #     - nwproject
  #   depend_on:
  #     - frontend
      # - backend
      # - database

  # my-database:
  #   build:
  #     dockerfile: ./docker/database.dockerfile
  #     context: .
  #     image: my-db:v1
  #     volume: 
  #       - pgdata
  #   networks:
  #     - nwproject

  web:
    build: ./web/
    # image: frontend:v1
    # container_name: frontend
    ports:
      - '8000'
    # network: nwproject
    volumes:
      - ./project:/app
    environment:
      - NODE_ENV=dev


  # backend:
  #   build:
  #     dockerfile: ./docker/backend.dockerfile
  #     context: .
  #     image: backend:v1
  #     container_name: backend
  #     ports:
  #       - '8000'
  #     network: nwproject

networks:
  nwproject:
    driver: bridge

# volumes:
#   pgdata: /var/lib/postgresql/data/