version: '3.8'
services:
  nginx:
    build: 
      dockerfile: ./proxy/Dockerfile
      context: .
    image: my-nginx:v1
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./project:/usr/share/nginx/html
  #   networks:
  #     - nwproject

      # - backend
      # - database

  # my-database:
  #   build: 
  #     dockerfile: ./databse/Dockerfile
  #     context: .
  #   image: my-db:v1
  #   networks:
  #     - nwproject
  #   volumes:
  #     - ./migrations:/flyway/sql/migrations:rw,z
  #   env_file: .environment
  
  web:
    build:
      dockerfile: ./web/Dockerfile
      context: .
    image: frontend:v1
    container_name: web
    ports:
      - '3000'
    # network: nwproject
    volumes:
      - ./project:/usr/src/app/
    environment:
      - NODE_ENV=dev
    depends_on:
      - nginx

  # backend:
  #   build:
  #     dockerfile: ./docker/backend.dockerfile
  #     context: .
  #     image: backend:v1
  #     container_name: backend
  #     ports:
  #       - '8000'
  #     network: nwproject

# networks:
#   nwproject:
#     driver: bridge

# volumes:
#   pgdata: /var/lib/postgresql/data/